### ISSUE TITLE
Fix .dockerignore icon being shown as .gitignore

### ISSUE THREAD

**Issue by tzinadah** [echasnovski/mini.nvim#1909]
### Contributing guidelines

- [x] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [x] I have updated 'mini.nvim' to latest version of the `main` branch

### Module(s)

mini.icons

### Neovim version

0.11.x

### Description

.dockerignore files are misrepresented with the git icon. Similar to the .prettierignore case where the vim api matches it to git ignore.

### Reproduction

Steps to Reproduce
1. Prerequisites

    A terminal with a Nerd Font installed and configured.

    A recent version of Neovim (v0.9+).

2. Minimal init.lua

Create a file named minimal_init.lua with the following content. This sets up lazy.nvim and installs only oil.nvim and mini.nvim.
```

-- bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- setup plugins
vim.api.nvim_set_keymap("n", "<leader>-", "<cmd>Oil<cr>", { desc = "Open parent directory" })

require("lazy").setup({
  -- Icon provider
  {
    "echasnovski/mini.nvim",
    config = function()
      require("mini.icons").setup()
    end,
  },

  -- File explorer
  {
    "stevearc/oil.nvim",
    opts = {
      view_options = {
        -- Show hidden files to see .dockerignore
        show_hidden = true,
      },
    },
  },
})
```
3. Create .dockerignore file and open neovim using the setup
4. Expected Result

The .dockerignore file and the Dockerfile should both display the Docker icon (󰡨).

5. Actual Result

The Dockerfile correctly displays the Docker icon (󰡨).
The .dockerignore file incorrectly displays the Git icon (󰊢).

**Comment by echasnovski** [comment]
Thanks for the issue! This should now be fixed on latest `main`.

This is a result of `vim.filetype.match()` detecting these files as 'gitignore' filetype, so this is more or less working as expected. But I agree that this is a bit confusing and there was already precedent with '.prettierignore'. So I decided to explicitly adjust all such files at once.

**Comment by tzinadah** [comment]
The same issue I think is still happening with docker-compose.yaml. Oil tries to get using "file" and since docker-compose is only identified under filetype it gets the yaml file icon.

**Comment by echasnovski** [comment]
> The same issue I think is still happening with docker-compose.yaml. Oil tries to get using "file" and since docker-compose is only identified under filetype it gets the yaml file icon.

This is *definitely* expected and won't be changed. It is [explicitly not a goal](https://github.com/echasnovski/mini.nvim/blob/c122e852517adaf7257688e435369c050da113b1/doc/mini-icons.txt#L31-L34) for 'mini.icons' to support as much special files cases as possible, which includes config files for all sorts of apps/technologies/languages/etc.

Users can adjust that by registering custom filetype detection rules (so that 'mini.icons' gets info from that filetype) and/or customize inside `require('mini.icons').setup()`.

Specifically for 'docker-compose.yml' file, 'mini.icons' [provides special icon data](https://github.com/echasnovski/mini.nvim/blob/c122e852517adaf7257688e435369c050da113b1/lua/mini/icons.lua#L1850), but it indeed requires custom filetype detection. For example, put something like this in the config:

```lua
vim.filetype.add({
  filename = {
    ['docker-compose.yml'] = 'yaml.docker-compose',
    ['docker-compose.yaml'] = 'yaml.docker-compose',
  },
})
```

**Comment by tzinadah** [comment]
Sorry I didn't phrase the issue well I used oil.nvim as an example for where I faced it. The issue is that this code
```
-- Basename extensions. Prefer this before `vim.filetype.match()` for speed
    -- (as the latter is slow-ish; like 0.1 ms in Neovim<0.11)
    local dot = string.find(basename, '%..', 2)
    if dot ~= nil then
      local ext = basename:sub(dot + 1):lower()
      if MiniIcons.config.use_file_extension(ext, name) == true then
        local icon, hl, is_default = MiniIcons.get('extension', ext)
        if not is_default then return icon, hl end
      end
    end
```
Makes it so the docker-compose.yaml file get identified as yaml and never goes to use the file type. It can be argued that the icon is not confusing as the rest in this issue as the file is indeed yaml, but it's not what the plugin is really intending as there is a specific docker-compose glyph in the file type table.  I really think that it should be added as a special file in the firs category here
 ```
-- Supported by `vim.filetype.match` but conflict with using extension first
  ['build.xml']           = 'ant',
  ['GNUmakefile.am']      = 'automake',
  ['Makefile.am']         = 'automake',
  ['makefile.am']         = 'automake',
  ['CMakeLists.txt']      = 'cmake',
  ['CMakeCache.txt']      = 'cmakecache',
  ['auto.master']         = 'conf',
  ['.oelint.cfg']         = 'dosini',
  ['.wakatime.cfg']       = 'dosini',
  ['pudb.cfg']            = 'dosini',
  ['setup.cfg']           = 'dosini',
  ['lltxxxxx.txt']        = 'gedcom',
  ['go.sum']              = 'gosum',
  ['go.work.sum']         = 'gosum',
  ['.indent.pro']         = 'indent',
  ['indent.pro']          = 'indent',
  ['ipf.rules']           = 'ipfilter',
  ['config.ld']           = 'lua',
  ['lynx.cfg']            = 'lynx',
  ['cm3.cfg']             = 'm3quake',
  ['maxima-init.mac']     = 'maxima',
  ['meson_options.txt']   = 'meson',
  ['.gitolite.rc']        = 'perl',
  ['example.gitolite.rc'] = 'perl',
  ['gitolite.rc']         = 'perl',
  ['main.cf.proto']       = 'pfmain',
  ['constraints.txt']     = 'requirements',
  ['requirements.txt']    = 'requirements',
  ['robots.txt']          = 'robots',
  ['tclsh.rc']            = 'tcl',
```
since it's a very popular file type that fails cause of the extension matching.
Sorry again for misrepresenting the issue and thank for your time and effort.

**Comment by echasnovski** [comment]
> I really think that it should be added as a special file in the firs category here

The problem is that this file is *not* supported by the `vim.filetype.match()`. This is a hard requirement to limit the amount of supported cases. If it will be supported directly by `vim.filetype.match()`, *then* it can be added to that table.

To make YAML files not use extension (which is there mostly for speed purposes) and instead rely on `vim.filetype.match()`, configure a dedicated [`config.use_file_extension`](https://github.com/echasnovski/mini.nvim/blob/c122e852517adaf7257688e435369c050da113b1/doc/mini-icons.txt#L257-L289). Here is what I use:

```lua
require('mini.icons').setup({
  use_file_extension = function(ext, _)
    local suf3, suf4 = ext:sub(-3), ext:sub(-4)
    return suf3 ~= 'scm' and suf3 ~= 'txt' and suf3 ~= 'yml' and suf4 ~= 'json' and suf4 ~= 'yaml'
  end,
})
```

Together with previous `vim.filetype.add`, this works.

**Comment by tzinadah** [comment]
Oh okay that seems reasonable. Thanks for your time and effort
