### ISSUE TITLE
mini.comment: error when commenting out empty line

### ISSUE THREAD

**Issue by kmarius** [echasnovski/mini.nvim#22]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

Toggling comment on an empty line results in 
```
E5108: Error executing lua ...nvim/site/pack/packer/opt/mini.nvim/lua/mini/comment.lua:129: Vim(lua):E5108: Error executing lua ...nvim/site/pack/pac
ker/opt/mini.nvim/lua/mini/comment.lua:320: attempt to index local 'indent' (a nil value)
```

### Neovim version

0.6

### Steps to reproduce

1. Toggle comment on an empty line (default `gcc`)

### Expected behavior

The line should be replaced with an empty comment.

### Actual behavior

The above error is thrown.

**Comment by echasnovski** [comment]
Thank you for bug report. Should be fixed now.

**Comment by mlhetland** [comment]
It seems the comment toggling still isn't working for the case where all lines are blank? I don't get an error, but I also don't get any comment toggling?

(Using LazyVim with default mini.comment setup. It works, and does comment out the empty lines when there are some non-empty ones mixed in.)

**Comment by mlhetland** [comment]
Ah, sorry, I see now that this is default behavior, also without mini.comment. (I was just used to different behavior from vim.) Would be nice to be able to have the commenting behavior be more consistent (i.e., still not ignoring empty lines when there are no non-empty ones; having a no-op keybinding isn't all that useful, IMO).

**Comment by echasnovski** [comment]
> Ah, sorry, I see now that this is default behavior, also without mini.comment. (I was just used to different behavior from vim.) Would be nice to be able to have the commenting behavior be more consistent (i.e., still not ignoring empty lines when there are no non-empty ones; having a no-op keybinding isn't all that useful, IMO).

If by "default" you mean coming from built-in Neovim's `gc` and `gcc`, then yes the behavior is the same. Mostly because the built-in one was heavily modeled by 'mini.comment'.

Not adding comment to only blank lines is [a documented behavior](https://github.com/echasnovski/mini.nvim/blob/8ca3965e68edfee5f438d4063f5adf5afa255884/doc/mini-comment.txt#L180-L183): "It uncomments if lines are comment (every line is a comment or blank) ...". The region with only blank lines is considered to be comment and the action is to uncomment (i.e. make it not comment), which in this case is the same as leaving them as is.

As I consider the action "comment blank lines" to be relatively niche, this looks acceptable to me. A better solution might be to [add an Insert mode mapping to insert comment leaders at cursor](https://github.com/echasnovski/mini.nvim/issues/1837#issuecomment-2934018027), but that is hard to do properly out of the box with 'mini.comment' (adding new mapping might break user's setups plus there is no good left hand side for such Insert mode mapping).

**Comment by mlhetland** [comment]
Right, right.

Well, I used it all the time in vim – especially in LaTeX. I just don't quite see how me using `gcc` on an empty line not doing anything is more useful than it doing something … but, yeah, I see that it's reasonable to model the built-in behavior. It also seems more consistent to me that the `ignore_blank_lines` option would apply regardless of the presence of non-blank lines – though I see that this can't be changed, given the origin of the behavior, and its established/documented status.

Some way of configuring whether one wants the built-in behavior or a consistent treatment of blank lines would be great, I guess … but I fully understand if that's not something you're interested in.

**Comment by echasnovski** [comment]
> Some way of configuring whether one wants the built-in behavior or a consistent treatment of blank lines would be great, I guess … but I fully understand if that's not something you're interested in.

The main point is that current behavior *is* consistent treatment, as was already described in [this comment](https://github.com/echasnovski/mini.nvim/issues/22#issuecomment-3018659494).

> I just don't quite see how me using `gcc` on an empty line not doing anything is more useful than it doing something …

It is more consistent with how an action is decided. Describing it as "uncomment if every line is comment or blank but not if all lines are blank, comment otherwise" is more confusing than the current behavior.

Aside from theoretical issues, there is also a practical one about deciding the indent of the added comment block. The indent is something computed as "whitespace from line start to first non-blank character", which requires a non-blank character. Treating the whole line as indent and adding comment leaders at the end of the widest blank line is something I don't really like to have.

**Comment by mlhetland** [comment]
Sorry for implying that the current behavior was inconsistent – that is certainly just a matter of perspective. It is certainly consistent with uncommenting when there's a mixture of comments and blanks. It's just not consistent with commenting when there's a mixture of non-comments and blanks – or toggling between the two?

At least I would have thought that the consistent thing to do would be to still toggle even if there is just a single blank line, just like one does with a single commented non-blank. I.e., if there is text on a line, `gcc` will add and remove the comment alternatively, but if there's a commented-out empty line, it will just remove the comment character and then become a no-op.

I understand the issue with the indent. The behavior I had in vim, and that seems to be the default in other plugins (though I haven't researched that thoroughly) is to just use an indent of 0, but … yeah. This is certainly an edge-case, and I see that your design here makes perfect sense. I just need a quick shortcut to comment out empty lines, but I'll manage that in some other way. Thanks.

**Comment by mlhetland** [comment]
(Ah, no, I was wrong about the 0. `Comment.nvim`, for example, uses a similar rule as the one you mentioned, but treats "end of line" the same way as non-blank, here, for the purposes of determining indentation.)

**Comment by mlhetland** [comment]
But to be clear: I completely agree that the behavior of `mini.comment` makes sense.
